#!/bin/bash

#PBS -l walltime=24:00:00,mem=22gb,nodes=1:ppn=16
#PBS -N hypred_simulations
#PBS -M neyha001@umn.edu
#PBS -m abe
#PBS -r n

# Change the working directory
cd /home/smithkp/neyhartj/Genomic_Selection/Simulations/BarleySimGS-TPUpdate

module load R


## Run the regular simulation

Rscript Code/run_experiment.R MN cumulative 100 50
#Rscript Code/run_experiment.R ND cumulative 100 50
#Rscript Code/run_experiment.R MNxND cumulative 100 50

#Rscript Code/run_experiment.R MN window 100 50
#Rscript Code/run_experiment.R ND window 100 50
#Rscript Code/run_experiment.R MNxND window 100 50

## Run using a smaller selection intensity
#Rscript Code/run_experiment.R MN cumulative 40 20
#Rscript Code/run_experiment.R ND cumulative 40 20
#Rscript Code/run_experiment.R MNxND cumulative 40 20

#Rscript Code/run_experiment.R MN window 40 20
#Rscript Code/run_experiment.R ND window 40 20
#Rscript Code/run_experiment.R MNxND window 40 20


## Run the allele frequency experiment

#Rscript Code/run_experiment_maf.R MN window
#Rscript Code/run_experiment_maf.R ND window
#Rscript Code/run_experiment_maf.R MNxND window
